openapi: 3.0.0
servers:
  - description: Customer API
    url: http://localhost:8290
info:
  description: "Sample rest api"
  version: "1.0.0"
  title: "Sample API"
  contact:
    email: "choreo-help@wso2.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: "customer"
    description: "customer api"
  - name: "demo"
    description: "This api is created for demo purposes"
paths:
  /HelloWorld:
    get:
      summary: "greeting with Hello"
      operationId: "Hello"
      description: |
        Greet the user
      responses:
        "200":
          description: "Greeting Message"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Greeting"

        "404":
          description: "Unable to Greet"

components:
  schemas:
    Greeting:
      type: object
      required:
        - helloMessage
      properties:
        HelloMessage:
          type: string
          example: "Hello World"
   